# Welcome to estampa! The minimum amount of settings you'll need to
# change to get your server working are:
#
# - base.host
# - mailbox.*
[base]
bind = "0.0.0.0:1958"
host = "localhost"
# This will be the location where estampa stores pretty much all of its
# data. Mailboxes, trusted servers, local certificates, etc. Keep this
# directory backed up and safe!
store = "./store/"

# If you're already hosting a Gemini capsule, change these settings
# below, so the paths point to its certificate and private key.
# Otherwise, the server will generate a pair automatically in those
# locations.
[tls]
certificate = "./server.crt"
private_key = "./server.key"

# Mailboxes are defined declaratively. In order to define your mailbox,
# you'll need to create a mailbox.* block. Here's an example:
#
# [mailbox.skye]
# enabled = true
# name = "Skylar"
#
# To break down which properties do what:
#
# - The "skye" value within the block will be the UID of your mailbox
#   (ex. skye@example.com)
#
# - "enabled" checks whether your account will be receiving any new
#   messages. If you've decided to move mailboxes, are getting lots of
#   spam, or just want to take a break from Misfin, you can set this
#   option to false, and messages from other users will be blocked.
#
# - "name" will be the fancy name of your mailbox. Set it to your own
#   (pseudo-)name!
