[package]
name = "estampa"
version = "0.1.0-alpha"
edition = "2021"
repository = "https://git.sr.ht/~nixgoat/estampa"
authors = ["Lux Aliaga <me@lux.rip>"]
license = "AGPL-3.0-or-later"

[dependencies]
rustls = "0.23"
rustls-pemfile = "2.1"
sha2 = "0.10"
thiserror = "1.0"
tokio-rustls = "0.26"
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.tokio]
version = "1.40"
features = ["io-util", "macros", "net", "rt-multi-thread"]
